#!/usr/bin/env bash
# ==============================================================================
# install.sh - Zero-touch Bootstrap Installer for Den1zzfiles
# Target OS: CachyOS x86_64
# ==============================================================================
#
# ⚠️  DISCLAIMER: This entire script is fully vibe-coded AI slop.
#     It was generated by an AI assistant and has NOT been manually
#     reviewed or battle-tested by a human. Use at your own risk.
#
#     It will be properly rewritten when the maintainer (Den1zz)
#     has the time to do so.
#
# ==============================================================================

set -euo pipefail

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
    echo -e "\033[1;33m[!] DRY-RUN MODE ENABLED: Mutating commands will be printed but not executed.\033[0m"
fi

# ------------------------------------------------------------------------------
# ⚠️  Runtime Warning
# ------------------------------------------------------------------------------
echo ""
echo -e "\033[1;31m╔══════════════════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[1;31m║                        ⚠️  WARNING ⚠️                            ║\033[0m"
echo -e "\033[1;31m╠══════════════════════════════════════════════════════════════════╣\033[0m"
echo -e "\033[1;33m║  This script is 100% vibe-coded AI slop.                       ║\033[0m"
echo -e "\033[1;33m║  It has NOT been manually reviewed or audited.                  ║\033[0m"
echo -e "\033[1;33m║                                                                ║\033[0m"
echo -e "\033[1;33m║  It will be rewritten when the maintainer (Den1zz) has the     ║\033[0m"
echo -e "\033[1;33m║  time to properly do so. Until then: proceed with caution.     ║\033[0m"
echo -e "\033[1;31m╚══════════════════════════════════════════════════════════════════╝\033[0m"
echo ""
read -rp "Do you understand the risks and wish to continue? [y/N] " confirm
if [[ "${confirm,,}" != "y" ]]; then
    echo "Aborted."
    exit 0
fi
echo ""

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
log_info() { echo -e "\033[1;34m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[1;32m[SUCCESS]\033[0m $1"; }
log_warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; }
log_err() { echo -e "\033[1;31m[ERROR]\033[0m $1"; exit 1; }

run() {
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "[DRY-RUN] $*"
    else
        "$@"
    fi
}

# ------------------------------------------------------------------------------
# Phase 1: Preflight Checks
# ------------------------------------------------------------------------------
log_info "Running Preflight Checks..."

# 1. Check for non-root user
if [[ "$EUID" -eq 0 ]]; then
    log_err "This script must be run as a standard user, not root. Standard sudo will be used where necessary."
fi

# 2. Check architecture
if [[ "$(uname -m)" != "x86_64" ]]; then
    log_err "Target architecture must be x86_64. Current: $(uname -m)"
fi

# 3. Check for CachyOS
if ! grep -qi "CachyOS" /etc/os-release; then
    log_warn "Target environment is CachyOS, but it wasn't detected in /etc/os-release. Proceeding anyway, but YMMV."
fi

# 4. Check Internet Access
if ! curl -s --head http://google.com >/dev/null; then
    log_err "No internet access detected. Please check your connection."
fi

log_success "Preflight checks passed."

# ------------------------------------------------------------------------------
# Phase 2: AUR Helper Detection (yay preferred, paru fallback)
# ------------------------------------------------------------------------------
AUR_HELPER=""
detect_aur_helper() {
    log_info "Detecting AUR helper (yay preferred, paru fallback)..."
    if command -v yay &> /dev/null; then
        AUR_HELPER="yay"
    elif command -v paru &> /dev/null; then
        AUR_HELPER="paru"
    else
        log_warn "No AUR helper found. Attempting to install yay from CachyOS repos..."
        run sudo pacman -S --needed --noconfirm yay
        if [[ $DRY_RUN -eq 1 ]]; then
            AUR_HELPER="yay"
        elif command -v yay &> /dev/null; then
            AUR_HELPER="yay"
        else
            log_warn "yay installation failed. Falling back to paru..."
            run sudo pacman -S --needed --noconfirm paru
            if command -v paru &> /dev/null || [[ $DRY_RUN -eq 1 ]]; then
                AUR_HELPER="paru"
            else
                log_err "Could not install any AUR helper (yay or paru). Install one manually and re-run."
            fi
        fi
    fi
    log_success "Using AUR helper: $AUR_HELPER"
}

detect_aur_helper

# ------------------------------------------------------------------------------
# Phase 3: Package Installations (pacman first, AUR helper as fallback)
# ------------------------------------------------------------------------------
log_info "Installing System Packages..."

# Helper: try installing a package via pacman first. If the package is not found
# in any enabled repo (including CachyOS repos), fall back to the AUR helper.
install_pkg() {
    local pkg="$1"
    if [[ $DRY_RUN -eq 1 ]]; then
        # In dry-run we still show the resolution logic
        if pacman -Si "$pkg" &> /dev/null; then
            echo "[DRY-RUN] sudo pacman -S --needed --noconfirm $pkg"
        else
            echo "[DRY-RUN] $AUR_HELPER -S --needed --noconfirm $pkg  (AUR fallback)"
        fi
        return
    fi

    if pacman -Si "$pkg" &> /dev/null; then
        run sudo pacman -S --needed --noconfirm "$pkg"
    else
        log_warn "'$pkg' not found in native repos — falling back to $AUR_HELPER (AUR)..."
        run "$AUR_HELPER" -S --needed --noconfirm "$pkg"
    fi
}

# We split packages into distinct groups for better readability and management.
BASE_PKGS=(
    "base-devel" "git" "curl" "wget" "tar" "unzip" "p7zip" "unrar" "xz" "zstd"
)

# Modern CLI Replacements (as identified in config.fish)
CLI_PKGS=(
    "fish" "eza" "bat" "zoxide" "fzf" "fd" "ripgrep" "dust" "btop"
    "micro" "atuin" "starship" "fastfetch" "uutils-coreutils"
)

# Wayland, Niri, and GUI Applications
GUI_PKGS=(
    "niri" "ghostty" "zed"
)

# Development Tools & Ecosystems
DEV_PKGS=(
    "nodejs" "npm" "python" "python-pip" "docker" "docker-compose"
    "kubectl" "kubectx" "github-cli"
)

# Fonts
FONT_PKGS=(
    "ttf-firacode-nerd" "ttf-nerd-fonts-symbols"
)

# Combine all desired packages into a single list
ALL_PKGS=("${BASE_PKGS[@]}" "${CLI_PKGS[@]}" "${GUI_PKGS[@]}" "${DEV_PKGS[@]}" "${FONT_PKGS[@]}")

# First, do a system update
log_info "Updating system via pacman..."
run sudo pacman -Syu --noconfirm

# Then install each package, automatically routing to AUR when needed
log_info "Installing packages (pacman first, AUR helper fallback)..."
for pkg in "${ALL_PKGS[@]}"; do
    install_pkg "$pkg"
done

# ------------------------------------------------------------------------------
# Phase 4: Dotfiles Symlinking (Idempotent & FHS Compliant)
# ------------------------------------------------------------------------------
log_info "Symlinking Dotfiles..."

CONFIG_SRC="$PWD/.config"
CONFIG_DEST="$HOME/.config"

run mkdir -p "$CONFIG_DEST"

symlink_config() {
    local src="$1"
    local dest="$2"
    
    if [[ -e "$dest" || -L "$dest" ]]; then
        if [[ "$(readlink "$dest" || true)" == "$src" ]]; then
            log_info "Symlink already correct: $dest -> $src"
            return
        fi
        local backup="${dest}.bak.$(date +%s)"
        log_warn "Backing up existing $dest to $backup"
        run mv "$dest" "$backup"
    fi
    
    run mkdir -p "$(dirname "$dest")"
    run ln -s "$src" "$dest"
    log_success "Symlinked $src -> $dest"
}

if [[ -d "$CONFIG_SRC" ]]; then
    for item in "$CONFIG_SRC"/*; do
        if [[ -e "$item" ]]; then
            base=$(basename "$item")
            symlink_config "$item" "$CONFIG_DEST/$base"
        fi
    done
else
    log_err ".config directory not found in the current workspace ($PWD/.config)."
fi

# Change default shell to fish
log_info "Changing default shell to fish..."
if [[ "$SHELL" != *"/fish"* ]]; then
    run sudo chsh -s "$(which fish)" "$USER"
    log_success "Default shell set to fish."
else
    log_info "Fish is already the default shell."
fi

# ------------------------------------------------------------------------------
# Phase 5: Health Check Suite
# ------------------------------------------------------------------------------
log_info "Running Health Check Suite..."

check_cmd() {
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "[DRY-RUN] Health Check: command -v $1"
    else
        if command -v "$1" &> /dev/null; then
            log_success "Command found: $1"
        else
            log_warn "Command missing: $1"
        fi
    fi
}

check_path() {
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "[DRY-RUN] Health Check: [ -e $1 ]"
    else
        if [[ -e "$1" ]]; then
            log_success "Path exists: $1"
        else
            log_warn "Path missing: $1"
        fi
    fi
}

# Verify essential tools
log_info "Verifying essential commands in PATH..."
for cmd in fish niri ghostty starship eza bat zoxide fd rg fzf uu-ls; do
    check_cmd "$cmd"
done

# Verify symlinks and configs
log_info "Verifying critical configuration files..."
check_path "$HOME/.config/fish/config.fish"
check_path "$HOME/.config/niri/config.kdl"
check_path "$HOME/.config/noctalia/settings.json"
check_path "$HOME/.config/starship.toml"

log_success "Bootstrap installation completed successfully!"
if [[ $DRY_RUN -eq 1 ]]; then
    log_info "This was a DRY-RUN. No system changes were made."
fi
